// Income approach. SNA 2008 ch.7 (distribution of income) — the generation of
// income account, summed over all resident producers.
//
// Identity implemented:
//   GDP at market prices
//     = compensation of employees (D.1)
//     + gross operating surplus (B.2g)
//     + gross mixed income (B.3g)
//     + taxes on production and imports (D.2)
//     − subsidies (D.3)
import type { Diagnostic, IncomeInput, IncomeResult, Money } from './types';
import { assertFinite, sum } from './numeric';

/**
 * The factor incomes generated by production. SNA 2008 ch.7: operating
 * surplus and mixed income are the balancing items of the generation of
 * income account — mixed income being the surplus of unincorporated
 * household enterprises, where the owner's labour and capital returns cannot
 * be separated.
 *
 * "Gross" throughout: before deduction of consumption of fixed capital.
 */
export function totalFactorIncomes(
  compensationOfEmployees: Money,
  grossOperatingSurplus: Money,
  grossMixedIncome: Money,
): Money {
  return sum([compensationOfEmployees, grossOperatingSurplus, grossMixedIncome]);
}

/**
 * Net taxes on production and imports. SNA 2008 ch.7. D.2 covers taxes on
 * products (D.21) plus other taxes on production (D.29); D.3 likewise covers
 * subsidies on products (D.31) plus other subsidies on production (D.39).
 * They enter GDP at market prices because market prices include them.
 */
export function netTaxesOnProductionAndImports(
  taxesOnProductionAndImports: Money,
  subsidies: Money,
): Money {
  return taxesOnProductionAndImports - subsidies;
}

/** GDP by the income approach. */
export function computeIncomeApproach(input: IncomeInput): IncomeResult {
  const diagnostics: Diagnostic[] = [];
  const fields: (keyof IncomeInput)[] = [
    'compensationOfEmployees',
    'grossOperatingSurplus',
    'grossMixedIncome',
    'taxesOnProductionAndImports',
    'subsidies',
  ];
  for (const field of fields) {
    assertFinite(input[field], field);
  }

  if (input.subsidies < 0) {
    diagnostics.push({
      code: 'component_missing',
      severity: 'warning',
      message:
        'Subsidies (D.3) were supplied as a negative amount. They are ' +
        'deducted by the engine, so a negative figure double-negates.',
      subject: 'subsidies',
    });
  }

  const factorIncomes = totalFactorIncomes(
    input.compensationOfEmployees,
    input.grossOperatingSurplus,
    input.grossMixedIncome,
  );
  const netTaxes = netTaxesOnProductionAndImports(
    input.taxesOnProductionAndImports,
    input.subsidies,
  );

  return {
    totalFactorIncomes: factorIncomes,
    netTaxesOnProductionAndImports: netTaxes,
    gdp: factorIncomes + netTaxes,
    diagnostics,
  };
}
